### ISSUE TITLE
Broken cpan release

### ISSUE THREAD

**Issue by amurf** [pmqs/Archive-Zip-SimpleZip#14]
This module is currently missing on cpan: https://metacpan.org/pod/Archive::Zip::SimpleZip

The latest commit which fixes the broken build 0321ab07c1ffcd644a0948b68a677f0be10300f1 seems to be missing in the version on cpan, so `t/000prereq.t` fails and it wont install for me on either Mac or Linux perl 5.30.

**Comment by pmqs** [comment]
Thanks @amurf, 

there are two issues then. 

Not clear why MetaCPAN doesn't have the module listed, For some reason the upload I did to CPAN last week  (0.037) didn't make it to MetaCPAN. I've re-uploaded 0.037 to CPAN and it seems to have fixed that issue.

Regarding 0321ab07c1ffcd644a0948b68a677f0be10300f1, I've just created a 0.038 release with that fix and uploaded to CPAN. I see it on MetaCPAN.

I'll close this ticket, but please contact me if you are still having problems.
