### ISSUE TITLE
Broken: missing lzma.h

### ISSUE THREAD

**Issue by Vlado-99** [pmqs/Archive-Zip-SimpleZip#18]
Can not install from CPAN because of missing lzma.h during compilation.
Version 0.039.

**Comment by pmqs** [comment]
Thanks for the report @Vlado-99 

The module is supposed to use LZMA , if it is available. For that to happen you need to have `IO::Compress::Lzma` & `Compress::Raw::Lzma` already installed.

Could you post a log of  the build process please? Include as much detail as possible.

**Comment by Vlado-99** [comment]
Manually copied content of terminal window:

[cpan.log](https://github.com/pmqs/Archive-Zip-SimpleZip/files/6710801/cpan.log)

Problem begins on line 863.
Running in Cygwin x64 under Windows 7 64bit. **

Tried to install IO::Compress::Lzma - log is here:
[IO-Compress-lzma.txt](https://github.com/pmqs/Archive-Zip-SimpleZip/files/6710833/IO-Compress-lzma.txt)

Next tried to install Compress::Raw::Lzma:

```
cpan[4]> install Compress::Raw::Lzma
Running install for module 'Compress::Raw::Lzma'
  PMQS/Compress-Raw-Lzma-2.101.tar.gz
  Has already been unwrapped into directory /home/vlado/.cpan/build/Compress-Raw-Lzma-2.101-1
  PMQS/Compress-Raw-Lzma-2.101.tar.gz
  Has already been prepared
  PMQS/Compress-Raw-Lzma-2.101.tar.gz
  Could not make: Unknown error
```

** I have tried Raspbian too - no success.

**Comment by Vlado-99** [comment]
There is nothing wrong with SimpleUnzip code itself: I borrowed your code from CPAN, made little tweaks (changed namespace), and it works perfectly. I work with ZIP archives containing many small files I need to process. I use extracting them one by one to memory buffer.

Your code helped to me a much. Thanks you!

**Comment by pmqs** [comment]
Good to hear you found a way around the issue and thanks for the kind words.
