### ISSUE TITLE
Error when i try extract file to full path

### ISSUE THREAD

**Issue by victor-bert** [pmqs/Archive-Zip-SimpleZip#2]
Error "Cannot create path 'home': File exists"
$member->extract('/home/dev023/app/d/m/d/e/zdev023/st/sh.pl');
Why you try make this dir w/o checking for exist?
Please, fix it

Maybe use File::Path::mkpath is better?
Or check directory existence (-e $dir and -d $dir) before try create it?

**Comment by pmqs** [comment]
Thanks @victor-bert, I'll deal with it.

**Comment by victor-bert** [comment]
Thanks.
Still noticed this error: after split/joins, the first slash for the file path is lost

**Comment by pmqs** [comment]
Fixes for this in 6b33be16c82fab8fe3f85b66c2bce21424960c55, d683c1d5f5e3c91bfd6beac3187cda6ca232d22c and
28135fa2228790e920e102fd444606c926444246
